# to run: docker compose up -d
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
# PLEX_CLAIM_ID=changeme
# 
#
version: "2"

services:
  # Transmission with OpenVPN configured
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - ALL
    ports:
      - "9091:9091"
      - "9117:9117"
      - "8191:8191"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      #- OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - NORDVPN_COUNTRY=GB
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=udp
      #- 'OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60'
      - LOCAL_NETWORK=10.20.0.0/24,192.168.1.0/24
    volumes:
      - ${MOUNT_POINT}/transmission:/data
      - ${MOUNT_POINT}/transmission/config:/conf
      - /etc/localtime:/etc/localtime:ro

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    depends_on:
      - "transmission"
      - "jackett"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    depends_on:
      - "transmission"
      - "jackett"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/plex/tv:/tv
      - ${MOUNT_POINT}/transmission/completed:/downloads

  # Jackett using the same OpenVPN connection that Transmission has.
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    depends_on:
      - "transmission"
    network_mode: container:transmission-openvpn
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
  #  ports:
  #    - "9117:9117"

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:
      - "transmission"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
   # ports:
   #   - "${PORT:-8191}:8191"
    restart: unless-stopped
    network_mode: container:transmission-openvpn
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - PLEX_CLAIM=${PLEX_CLAIM_ID}
    volumes:
      - ${MOUNT_POINT}/plex/plex-config:/config
      - ${MOUNT_POINT}/plex/transcode:/transcode 
      - ${MOUNT_POINT}/plex:/data
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - plexnet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/bazarr/config:/config
      - ${MOUNT_POINT}/plex/movies:/movies
      - ${MOUNT_POINT}/plex/tv:/tv 
    ports:
      - 6767:6767
    restart: always


  network-multitool:
    image: praqma/network-multitool
    container_name: network-multitool
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    depends_on:
      - "transmission"
#    networks:
#      - plexnet
    network_mode: container:transmission-openvpn
    restart: unless-stopped
networks:
  plexnet:
    driver: bridge
  
